### ISSUE TITLE
Bookdown Docs folder

### ISSUE THREAD

**Issue by rosstox26** [rorymeyer/KRYRK#2]
Two quick things:
1. Your bookdown content should be on the root rather than inside the sub-folder
2. You need to publish to the "docs" folder for GitHub to recognize where to get the published version from. Refer to section 6.3 https://bookdown.org/yihui/bookdown/github.html

**Comment by rorymeyer** [comment]
To fix the second problem, I followed these steps from the bookdown link you posted:

"One approach is to publish your book as a GitHub Pages site from a /docs folder on your master branch as described in [GitHub Help.](http://bit.ly/2cvloKV) First, set the output directory of your book to be /docs by adding the line output_dir: "docs" to the configuration file _bookdown.yml. Then, after pushing your changes to GitHub, go to your repository’s settings and under “GitHub Pages” change the “Source” to be “master branch /docs folder”. In this case, the .nojekyll file has to be in the /docs folder."

I think I fixed it, but please let me know if you see more issues.

What is the best way to fix the first problem?

**Comment by rosstox26** [comment]
Rory - see the folder structure here: https://github.com/gthuiz/MBAnCareerPulse

We are looking for the docs folder to be a subfolder of root directory. Right now docs is inside the KRYRK Guide to Ann Arbor folder.

The docs folder is looking fine.

**Comment by rorymeyer** [comment]
I think I fixed it! Will you let me know if it looks good on your end?

**Comment by rosstox26** [comment]
Looks wonderful Rory. You may want to put a link to your published site in your readme - I think its https://rorymeyer.github.io/KRYRK/

Great job! I am closing this issue.
