### ISSUE TITLE
Commits

### ISSUE THREAD

**Issue by rosstox26** [rorymeyer/KRYRK#4]
I see commits by only a couple people. I would like rest of the group to be active in pushing content please. Close this issue when all the members of the team have made at least one commit to the repo.

**Comment by rorymeyer** [comment]
<img width="1680" alt="Screen Shot 2022-07-25 at 1 03 10 PM" src="https://user-images.githubusercontent.com/109174506/180834351-1b8056fc-a936-47a5-9237-e8473d5514b5.png">
Hi! Everyone was responsible for committing/pushing their own about me pages to the repo. So, I'm not sure why it's not showing on the commits page that everyone has contributed, but in the screenshot I included it shows that all 5 authors have made at least one commit to the repo.
